spring.application.name=backend

# Render Cloud Database Configuration Mapped via Environment Variables
spring.datasource.url=jdbc:postgresql://ep-soft-waterfall-a4t9bbmw-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jugwz0JhEcf2
spring.datasource.driver-class-name=org.postgresql.Driver

# Production JPA Data Structure Strategy
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Internal Port Mapping
server.port=${PORT:8080}
